version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    command: bash -c "cargo run"
  #command: ["cargo", "watch", "-x", "run"]
    depends_on:
      - dbpg
